/// <reference types="cypress" />

const testId = (id) => `[data-testid="${id}"]`
const NAV_HOME = testId('button-home-page')
const NAV_CREATE = testId('button-form-page')
const BUTTON_SAVE = testId('button-save')
const BUTTON_CANCEL = testId('button-cancel')
const BUTTON_DELETE = testId('button-delete')
const BUTTON_SET_DELETE = testId('button-set-delete')
const BUTTON_EDIT = testId('button-edit')
const BUTTON_DETAILS = testId('button-details')

describe('overview page', function () {
  it('shows empty page at first render', () => {
    // cy.get('header')
    // cy.get('h1')
    // cy.get('footer')
    cy.get(NAV_HOME)
    cy.get(NAV_CREATE)
    cy.contains('Player(s)').should('not.exist')
    cy.contains('Winner(s)').should('not.exist')
    cy.contains('Total Shots Winner(s)').should('not.exist')
    cy.get(BUTTON_SET_DELETE).should('not.exist')
    cy.get(BUTTON_EDIT).should('not.exist')
    cy.get(BUTTON_DETAILS).should('not.exist')
  })
})

describe('create page', function () {
  it('creates a new game', () => {
    cy.visit('/')
    cy.get(NAV_CREATE).click()
    cy.url().should('include', '/create')
    cy.get(BUTTON_SAVE).should('be.disabled')
    cy.get(BUTTON_CANCEL).should('be.enabled')
    cy.get('h3')
    cy.contains('Location').type('City Park')
    cy.contains('Date').type('2020-12-24')
    cy.contains('Player(s)').type('Sarah, Hannes')
    cy.contains('Winner(s)').type('Sarah')
    cy.contains('Total Shots Winner(s)').type('28')
    cy.contains(
      '*Please do not clear your browsers cache, in order to permanently save your game details'
    )
    cy.get(BUTTON_SAVE).should('be.enabled')
    cy.get(BUTTON_SAVE).click()
    cy.url().should('include', '/create')
    cy.get(BUTTON_SAVE).should('be.disabled')
    cy.get(BUTTON_CANCEL).should('be.enabled')
    cy.get('h3')
    cy.contains('Holes')
    cy.contains('1')
    cy.contains('18')
    cy.contains('Sarah')
    cy.contains('Hannes')
    cy.get('input')
      .should('have.length', 36)
      .each((el) => cy.wrap(el).type('2'))
    cy.get(BUTTON_SAVE).should('be.enabled')
    cy.get(BUTTON_SAVE).click()
    cy.url().should('not.include', '/create')
    cy.contains('City Park')
    cy.contains('2020-12-24')
    cy.contains('Sarah, Hannes')
    cy.contains('Sarah')
    cy.contains('28')
    cy.get(BUTTON_SET_DELETE)
    cy.get(BUTTON_EDIT)
    cy.get(BUTTON_DETAILS)
  })
})

describe('game', function () {
  beforeEach(() => {
    cy.visit('/')
  })

  it('redirects to details page on info button click', () => {
    cy.get(BUTTON_DETAILS).click()
    cy.url().should('include', '/details')
  })

  it('redirects to edit page on pen button click', () => {
    cy.get(BUTTON_EDIT).click()
    cy.url().should('include', '/edit')
  })

  it('deletes game on bin button click', () => {
    cy.get(BUTTON_SET_DELETE).click()
    cy.contains('Do you really want to delete this game?')
    cy.get(BUTTON_DELETE)
    cy.get(BUTTON_CANCEL)
    cy.contains('City Park').should('not.exist')
    cy.contains('2020-12-24').should('not.exist')
    cy.contains('Sarah, Hannes').should('not.exist')
    cy.contains('Sarah').should('not.exist')
    cy.contains('28').should('not.exist')
    cy.get(BUTTON_SET_DELETE).should('not.exist')
    cy.get(BUTTON_EDIT).should('not.exist')
    cy.get(BUTTON_DETAILS).should('not.exist')
    cy.get(BUTTON_DELETE).click()
    cy.contains('City Park').should('not.exist')
    cy.contains('2020-12-24').should('not.exist')
    cy.contains('Sarah, Hannes').should('not.exist')
    cy.contains('Sarah').should('not.exist')
    cy.contains('28').should('not.exist')
    cy.get(BUTTON_SET_DELETE).should('not.exist')
    cy.get(BUTTON_EDIT).should('not.exist')
    cy.get(BUTTON_DETAILS).should('not.exist')
  })

  it('does not delete game after clicking on bin and cancel button', () => {
    cy.get(BUTTON_SET_DELETE).click()
    cy.contains('Do you really want to delete this game?')
    cy.get(BUTTON_DELETE)
    cy.get(BUTTON_CANCEL)
    cy.contains('City Park').should('not.exist')
    cy.contains('2020-12-24').should('not.exist')
    cy.contains('Sarah, Hannes').should('not.exist')
    cy.contains('Sarah').should('not.exist')
    cy.contains('28').should('not.exist')
    cy.get(BUTTON_SET_DELETE).should('not.exist')
    cy.get(BUTTON_EDIT).should('not.exist')
    cy.get(BUTTON_DETAILS).should('not.exist')
    cy.get(BUTTON_CANCEL).click()
    cy.contains('City Park')
    cy.contains('2020-12-24')
    cy.contains('Sarah, Hannes')
    cy.contains('Sarah')
    cy.contains('28')
    cy.get(BUTTON_SET_DELETE)
    cy.get(BUTTON_EDIT)
    cy.get(BUTTON_DETAILS)
  })
})

describe('navigation', function () {
  it('redirects to create page on plus button click', () => {
    cy.visit('/')
    cy.get(NAV_CREATE).click()
    cy.url().should('include', '/create')
  })

  it('redirects to overview page on home button click', () => {
    cy.visit('/create')
    cy.get(NAV_HOME).click()
    cy.url().should('include', '/')
    cy.url().should('not.include', '/create')
  })
})
